# Makefile

# Directories and file names

TARGETS := cache_L1associativity_benchmark cache_L2associativity_benchmark cache_L3associativity_benchmark

# Default target
all: $(TARGETS)

cache_L1associativity_benchmark: L1_associativity_benchmark.c
	gcc -o0 L1_associativity_benchmark.c -o cache_L1associativity_benchmark

cache_L2associativity_benchmark: L2_associativity_benchmark.c
	gcc -o0 L2_associativity_benchmark.c -o cache_L2associativity_benchmark

cache_L3associativity_benchmark: L3_associativity_benchmark.c
	gcc -o0 L3_associativity_benchmark.c -o cache_L3associativity_benchmark

