max_time = 1  # maximum time for each benchmark
thread_counts = [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 32, 48]  # virtual cores the tests runs
prime_numbers = [1000, 5000, 10000, 20000, 30000, 50000, 100000] #benchmark limit, each for a new colored line on the graph
